name: Build project

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  # Checks Unity license.
  checklicense:
    name: Check for UNITY_LICENSE in GitHub Secrets
    runs-on: ubuntu-latest
    outputs:
      is_unity_license_set: ${{ steps.checklicense_job.outputs.is_unity_license_set }}
    steps:
      - name: Check whether Unity activation should be done
        id: checklicense_job
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
          if [[ -n "${UNITY_LICENSE}" ]]; then
            echo "is_unity_license_set=true" >> $GITHUB_OUTPUT
          else
            echo "is_unity_license_set=false" >> $GITHUB_OUTPUT
          fi

  format_check:
    uses: ./.github/workflows/format.yaml

  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    needs: [checklicense, format_check]
    if: needs.checklicense.outputs.is_unity_license_set == 'true'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      # Checkout.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache Unity Library folder.
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: ./.github/actions/nugetforunity-restore
        with:
          working-directory: .

      # Build project.
      - name: Build Unity Project
        id: unity_build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      # Print Unity build log to the console if the build failed.
      - name: Print Unity Build Log to console
        if: always() && steps.unity_build.outcome == 'failure'
        run: |
          echo "=== UNITY BUILD LOG ==="
          Get-Content "${{ steps.unity_build.outputs.logPath }}" -Raw # Corrected command for PowerShell
        shell: powershell

      # Upload Unity build log as an artifact if the build failed.
      - name: Upload Unity Build Log on failure
        if: always() && steps.unity_build.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: UnityBuildLog-${{ matrix.targetPlatform }}
          path: ${{ steps.unity_build.outputs.logPath }}
          retention-days: 7
